[package]
name = "bitcask-kv"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5"
crc32fast = "1.4"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"

[dev-dependencies]
tempfile = "3.8"
rand = "0.8"
